### PR TITLE
Assorted tweaks

### PR DESCRIPTION
**Pull request by MattIPv4**
- Set a blue background for the game, akin to Slay
 - Give the world a nice drop shadow
 - Make the player color green, friendlier than red
 - Tweak gold glow, so it pulses instead of snapping
 - Right-click buys/upgrades units if a kingdom is selected, akin to Slay
 - Added an "insane" world size, cause I got bored of the big size
 - Added some new building artwork, so they're actually buildings
 - Game freezes state when a kingdom wins
 - Show the selected unit attached to the mouse cursor

Possibly TODO:
 - Win/defeat popup (`Arbiter.checkWon()`)
 - Investigate why the game feels super laggy
 - Investigate CI failures

### CODE REVIEW

**Comment by MattIPv4** [comment]
Travis seems to be failing on a unit test, not very familiar with the test suite or why those tests are failing. Would appreciate some help on that.

**Comment by alcalyn** [comment]
Hi, thank you that's nice ! I like how the select item is displayed next to the mouse

- About the new design, feel free to totally remove old ones (instead of moving them as `.old` files), I choose it quickly to have something to develop so no matter to keep it
- I think the sea blue is too dark, maybe a light blue like "lightblue" or "aquamarine" would be better ?

For todos, I created #5 and #6

**Comment by alcalyn** [comment]
About unit tests that is failing, they are already failing on master, so you can ignore them for this pr.

I think one is a TDD test but the actual bug is not fixed, the other one is a bug that cause the state of the game inconsistent, two instance of kingdom are created for a single visible one

**Comment by MattIPv4** [comment]
Sweet, sounds good!
Did some cleanup, this should be good to go for a full review :)

(Would love to add my +1 to https://github.com/alcalyn/openhex/projects/1#card-8243627)

**Comment by alcalyn** [comment]
Thanks @MattIPv4 !

I will create issues instead of project cards to be able to upvote and track them

**Pull request merged**
